### PR TITLE
Fix print_buffer

### LINKED ISSUE #13: Multiple uses of `test_helper::render_view` lead to crashes in tests.
I've duplicated the `simple_block_test` test and it crashes with something like:

```
thread 'view::block::tests::simple_block_test' panicked at src/test_helper.rs:50:45:
called `Option::unwrap()` on a `None` value
```

But it seems to be enough to just duplicate:
```rust
let buffer = render_view(
    Size {
        width: 15,
        height: 5,
    },
    sut.clone(),
    AppState,
);
```
in the test to reproduce this.

@zoechi can you take a look at this?

### PR DESCRIPTION
**Pull request by zoechi**
It's still not perfect, but I think it's pretty useful already. A nuisance is that the test output starts immediately after the last character in the last line of the widget.
I haven't found a way to prevent that.

### CODE REVIEW

File: src/test_helper.rs [hunk 1]
```diff
@@ -208,26 +205,24 @@ impl Widget for DebugWidget {
...
             CrosstermBackend::new(stdout()),
             TerminalOptions {
-                viewport: Viewport::Inline(buffer.area.height),
+                viewport: Viewport::Fixed(buffer.area),
             },
         )?;
+
+        terminal.clear()?;
         terminal.current_buffer_mut().clone_from(buffer);
         terminal.flush()?;
```
Comment (Philipp-M) [inline src/test_helper.rs:229]: You can add the following to get to the beginning of the next line:

```suggestion
        terminal.flush()?;
        crossterm::queue!(stdout(), crossterm::cursor::MoveTo(0, buffer.area.height))?;
```

Comment (zoechi) [reply src/test_helper.rs:229]: Sounds good. I'll try.

**Review by Philipp-M — APPROVED** [review]
Thanks for the fix. LGTM :)
